server:
  port: 10086
  servlet:
    context-path: /community

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 300000
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mail:
    host: smtp.sina.com
    username: 0527cyqdyx@sina.com
    password: 3a2d0362e691d1dc
    protocol: smtps
    port: 465
    properties:
      mail:
        smtp:
          auth: true



mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.cyq.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
#    mapUnderscoreToCamelCase: true
logging:
  level:
    com.cyq.community: debug

#  community
community:
  path:
    domain: localhost:10086/community